### ISSUE TITLE
button disabled字体颜色样式无法更改

### ISSUE THREAD

**Issue by MarcWong** [Meituan-Dianping/mpvue#1062]
通过以下css代码修改button disabled被激活时的样式，但只有背景色修改有效，字体颜色未被修改，请问是什么问题？该如何解决？

``` css
button[disabled]::after {
    color: #fff;
    opacity: 1;
    background-color: #999;
}
```
mpvue版本1.0.13，不知道大家有没有遇到类似的问题

暂时的解决方法是通过v-if判断disabled强行设置css。。
