### ISSUE TITLE
mpvue中怎样监听微信官方custom-tab-bar的triggerEvent

### ISSUE THREAD

**Issue by HughDai** [Meituan-Dianping/mpvue#1714]
## mpvue中监听自定义组件custom-tab-bar的triggerEvent

**mpvue 版本号：**

[mpvue@2.0.6]

**问题复现步骤：**
点击扫码按钮

**观察到的表现：**
1. 使用custom-tab-bar作自定义tabbar，tab的跳转功能都已经实现，并在tab里添加一个按钮实现扫码功能，样式上也绕过cover-view不支持overflow: visible的缺陷，现在想在宿主page里监听组件中扫码点击事件。
2. 由于没有显示引用custom-tab-bar组件，无法在组件上直接bind事件。组件triggerEvent，page里接收不到。

![1566964100248](https://user-images.githubusercontent.com/4846040/63824470-d69fa500-c989-11e9-8cb1-06503578ccef.jpg)

## 请问有没有高手遇到同样的问题，怎样解决的

**最小化复现代码：**

// 示例代码：
``` js
// custom-tab-bar/index.js
/* eslint-disable no-undef */
Component({
  data: {
    selected: 0,
    color: '#999999',
    selectedColor: '#333333',
    list: [{
      pagePath: '/pages/index/main',
      iconPath: '../static/tabs/tab-home.png',
      selectedIconPath: '../static/tabs/tab-home-active.png',
      text: '首页'
    }, {
      pagePath: '/pages/account/main',
      iconPath: '../static/tabs/tab-account.png',
      selectedIconPath: '../static/tabs/tab-account-active.png',
      text: '我的'
    }],
    iconScanPath: '../static/tabs/icon-scan.png'
  },
  attached () {
    console.info('Component loaded!')
  },
  detached () {
    console.info('Component unloaded!')
  },
  methods: {
    switchTab (e) {
      console.log(e)
      const data = e.currentTarget.dataset
      const url = data.path
      wx.switchTab({url})
      this.setData({
        selected: data.index
      })
      console.log(data)
    },
    handleScan (e) {
      console.log('scan')
      console.log(this)
      this.triggerEvent('scanevent')
    }
  }
})
```
``` html
// custom-tab-bar/index.wxml
<cover-view class="tab-bar">
  <!--<cover-view class="tab-bar-border"></cover-view>-->
  <cover-view class="tab-bar-view">
    <cover-view wx:for="{{list}}" wx:key="index" class="tab-bar-item" data-path="{{item.pagePath}}" data-index="{{index}}" bindtap="switchTab">
      <cover-image src="{{selected === index ? item.selectedIconPath : item.iconPath}}"></cover-image>
      <cover-view style="color: {{selected === index ? selectedColor : color}}">{{item.text}}</cover-view>
    </cover-view>
  </cover-view>
  <cover-view class="scan-view" bindtap="handleScan">
    <cover-image src="{{iconScanPath}}"></cover-image>
    <cover-view class="scan-text">扫码买单</cover-view>
  </cover-view>
</cover-view>
```
```css
// custom-tab-bar/index.wxss
cover-view {
  visibility: visible !important;
  overflow: visible !important;
}

.tab-bar {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  height: 78px;
  display: flex;
  justify-content: center;
  align-items: flex-end;
  padding-bottom: env(safe-area-inset-bottom);
}

.tab-bar-view {
  display: flex;
  width: 100%;
  height: 48px;
  background: #FAFAFA;
}

.tab-bar-item {
  flex: 1;
  text-align: center;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
}

.tab-bar-item cover-image {
  width: 27px;
  height: 27px;
}

.tab-bar-item cover-view {
  margin-top: 6px;
  font-size: 10px;
}

.scan-view {
  background: transparent;
  position: absolute;
  transform: translateY(-10px);
  text-align: center;
}

.scan-view cover-image {
  width: 40px;
  height: 40px;
  margin: 0 auto;
}

.scan-view .scan-text {
  margin-top: 6px;
  font-size: 10px;
  color: #333333;
}
```
```js
// pages/index/index.vue
onShow () {
    console.log(this.$mp.page)
    this.$mp.page.ontap = function (e) {
      console.log(e)
    }
    const { getTabBar } = this.$mp.page
    if (typeof getTabBar === 'function') {
      this.$mp.page.getTabBar().setData({
        selected: 0
      })
    }
  }
```

```json
// pages/index/main.json
{
  "navigationBarTitleText": "小程序demo",
  "usingComponents": {}
}
```
