### ISSUE TITLE
postcss-mpvue-wxss过滤还有待完善啊

### ISSUE THREAD

**Issue by zjz894251se** [Meituan-Dianping/mpvue#39]
```css
@-moz-document url-prefix() {
@media print {
    .application {
      display: block;
    }
    .application--wrap {
      display: block;
    }
}
}
```
@media print 小程序不支持,没过滤掉
