### ISSUE TITLE
props默认值

### ISSUE THREAD

**Issue by liumin1128** [Meituan-Dianping/mpvue#486]
# [问题简单描述]

视乎不支持props默认值 
```
export default {
    props: {
      color: {
        default: 'black',
      },
      type: {
        default: 'circle',
      },
    },
  };
```
组件内这样写不生效

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by F-loat** [comment]
这个应该是支持的，你再检查下写法

**Comment by aOrz** [comment]
实测支持，如果还有问题，请提供更详细的描述和 demo，谢谢

**Comment by F-loat** [comment]
好像说只有 prop 没有 data 会有问题？

**Comment by aOrz** [comment]
@F-loat 试了下，没问题

**Comment by ldwonday** [comment]
```js
<template>
  <divc class="loading" v-if="!isShow">
    <img src="../assets/images/loading.gif" />
    <div>{{loadingText}}</div>
  </divc>
</template>
<script>
  export default {
    props: {
      loadingText: {
        type: String,
        default: '正在加载...'
      },
      isShow: {
        type: Boolean,
        default: false
      }
    },
    mounted () {
      console.log(this)
    }
  }
</script>
```
这个loadingText为什么取不到？

**Comment by shaonialife** [comment]
@ldwonday 你的 divc 能有效就有鬼了

**Comment by ldwonday** [comment]
@shaonialife 注意到这个问题，修改了还是出不来！

**Comment by ldwonday** [comment]
![image](https://user-images.githubusercontent.com/4630157/41758095-f1e8b006-7618-11e8-86a9-76644ff7aa23.png)

**Comment by shaonialife** [comment]
我这里都是好好的, 很正常

**Comment by ldwonday** [comment]
@shaonialife 我更新了代码，截图是真是的运行结果！

**Comment by ldwonday** [comment]
我找了问题，组件命名的问题，原来用的Loading，现在把组件的名字修改成了CustomLoading，都正常了，但是那个v-if换成v-show还是不行，无法正常运行。

**Comment by shaonialife** [comment]
你检查一下你的视图, 当v-show为false 时, 有以下样式吗
![image](https://user-images.githubusercontent.com/16135960/41758452-47e9709c-761b-11e8-891d-0b453bad4d93.png)

**Comment by ldwonday** [comment]
@shaonialife 
```css
.loading.data-v-ac9eb9ae {
./static/css/pages/index/main.wxss:26display:flex;
justify-content:center;
align-items:center;
padding:20rpx;
background:#f7f7f7;

}
view[hidden] {
display:none;

}
view {
display:block;
}
```

**Comment by ldwonday** [comment]
![image](https://user-images.githubusercontent.com/4630157/41758675-dd84ae9a-761c-11e8-8e89-93cbf2812b3c.png)
![image](https://user-images.githubusercontent.com/4630157/41758682-e3db1fc2-761c-11e8-861d-c5fd03c11419.png)
我真的要疯了，这个loading为什么放到第一个去了？

**Comment by shaonialife** [comment]
@ldwonday  刚才我看了一下, 你的样式怎么是在 ./static/css/pages/index/main.wxss 下的, 不应该是在./static/css/vendor.wxss 下面吗
你是不是在这个页面引入了Loading里的样式, 导致优先级变了

**Comment by shaonialife** [comment]
@ldwonday 这个是没有问题的, 因为你这个Loading 是第一个渲染的, 虽然显示在第一个, 但是位置仍然在最后面

**Comment by ldwonday** [comment]
@shaonialife 没有引入，因为我组件用了scoped，所以出现在页面的wxss里面，还有你说的虽然显示在第一个，实际也是第一个，我又外面包了一层div解决了

**Comment by shaonialife** [comment]
我组件也是用的 scoped 啊, 没有任何问题啊

**Comment by ldwonday** [comment]
@shaonialife 难道我们用的不是一个版本的？我删掉dist重新编译一样的结果！flex会覆盖none

**Comment by shaonialife** [comment]
@ldwonday 我错了, 确实在添加 scoped 的情况下会被覆盖, 解决这个问题也是蛮简单的, 就是在 App.vue 下面 添加 
```css
view[hidden] {
   display: none !important;
}
```
同理, 解决其他标签也是这样
```css
view[hidden], image[hidden] {
   display: none !important;
}
```
理论上, 把所有小程序的标签都写上, 就彻底解决这类问题了
