### ISSUE TITLE
如何避免样式全局

### ISSUE THREAD

**Issue by oksite** [Meituan-Dianping/mpvue#691]
```css
<style>
page{
  width: 100%;
  height: 100%;
  overflow-x: hidden;
  overflow-y: scroll;
  -webkit-font-smoothing: antialiased;
  font-family: Helvetica Neue, Helvetica, STHeiTi, sans-serif;
  font-size: 13px;
  color: #333333;
  background: #F5F5F5;
}
</style>
<style scoped lang="less">
 .address{
     float: left;
    width: 100%;
    background:white;
    margin-top: 10px;
}
</style>
```
